package com.smartservice.nomina.util;


public enum ConceptEnum {
    DAYS_BASIC_CONCEPT,
    DISCOUNT_TRANSPORTATION_ALLOWENCE,
    EXTRA_HOUR,
    HEALTH,
    INABILITY_COMPANY,
    INABILITY_EPS,
    LICENSE,
    RETIRE,
    SALARY,
    SOLIDARITY_FOUND,
    TRANSPORTATION_ALLOWENCE,
    INABILITY_ACCIDENT_JOB_ADMIN,
    INABILITY_ACCIDENT_JOB_COMPANY,
    VACATIONS,
    VALOR
}
